
package pooherencia;


public class Interfaz extends javax.swing.JFrame {
      Poocalcu Operar = new Poocalcu();
      
      
      double numero1;
      double numero2;
      double uniconumero;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
       
        initComponents();
        
    }
     
    public void entrada(){
       numero1 = Double.parseDouble(primer1.getText());
        numero2 = Double.parseDouble(segundo1.getText());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        segundo1 = new javax.swing.JTextField();
        primer1 = new javax.swing.JTextField();
        btnsuma = new javax.swing.JButton();
        btnresta = new javax.swing.JButton();
        btnmultiplicacion = new javax.swing.JButton();
        btndivision = new javax.swing.JButton();
        btnpotencia = new javax.swing.JButton();
        resultadotxt = new javax.swing.JTextField();
        btnlogaritmo = new javax.swing.JButton();
        btnraizcubica = new javax.swing.JButton();
        btnraizcuadrada = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setFocusable(false);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("primer numero");

        jLabel2.setBackground(new java.awt.Color(51, 255, 204));
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("segundo numero");

        segundo1.setBackground(new java.awt.Color(0, 255, 0));
        segundo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundo1ActionPerformed(evt);
            }
        });

        primer1.setBackground(new java.awt.Color(51, 255, 51));
        primer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primer1ActionPerformed(evt);
            }
        });

        btnsuma.setBackground(new java.awt.Color(255, 51, 51));
        btnsuma.setForeground(new java.awt.Color(153, 255, 0));
        btnsuma.setText("+");
        btnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumaActionPerformed(evt);
            }
        });

        btnresta.setBackground(new java.awt.Color(255, 51, 51));
        btnresta.setForeground(new java.awt.Color(0, 255, 51));
        btnresta.setText("-");
        btnresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaActionPerformed(evt);
            }
        });

        btnmultiplicacion.setBackground(new java.awt.Color(0, 255, 51));
        btnmultiplicacion.setForeground(new java.awt.Color(255, 0, 0));
        btnmultiplicacion.setText("x");
        btnmultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplicacionActionPerformed(evt);
            }
        });

        btndivision.setBackground(new java.awt.Color(255, 51, 51));
        btndivision.setForeground(new java.awt.Color(51, 255, 0));
        btndivision.setText("/");
        btndivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivisionActionPerformed(evt);
            }
        });

        btnpotencia.setBackground(new java.awt.Color(255, 51, 51));
        btnpotencia.setForeground(new java.awt.Color(51, 51, 255));
        btnpotencia.setText("potencia");
        btnpotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpotenciaActionPerformed(evt);
            }
        });

        resultadotxt.setEditable(false);
        resultadotxt.setText("resultado");
        resultadotxt.setCaretColor(new java.awt.Color(51, 51, 255));
        resultadotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadotxtActionPerformed(evt);
            }
        });

        btnlogaritmo.setBackground(new java.awt.Color(255, 51, 51));
        btnlogaritmo.setForeground(new java.awt.Color(51, 255, 0));
        btnlogaritmo.setText("log");
        btnlogaritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogaritmoActionPerformed(evt);
            }
        });

        btnraizcubica.setBackground(new java.awt.Color(255, 51, 51));
        btnraizcubica.setForeground(new java.awt.Color(51, 51, 255));
        btnraizcubica.setText("raizcubica");
        btnraizcubica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnraizcubicaActionPerformed(evt);
            }
        });

        btnraizcuadrada.setBackground(new java.awt.Color(255, 51, 51));
        btnraizcuadrada.setForeground(new java.awt.Color(51, 51, 255));
        btnraizcuadrada.setText("raizcuadrada");
        btnraizcuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnraizcuadradaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setText("CE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnpotencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultadotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(segundo1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(primer1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(btnraizcubica)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnresta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnmultiplicacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)))
                                    .addComponent(btnraizcuadrada))))
                        .addGap(5, 5, 5)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnsuma, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btndivision, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnlogaritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGap(402, 402, 402))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsuma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(segundo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndivision, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnresta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnraizcubica, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnraizcuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlogaritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadotxt))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void segundo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segundo1ActionPerformed

    private void primer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primer1ActionPerformed

    private void btnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumaActionPerformed
        double n1 = Double.parseDouble(primer1.getText());
        double n2 = Double.parseDouble(segundo1.getText());
        double resultado = Operar.suma(n1, n2);
        resultadotxt.setText(String.valueOf(resultado));
        
    }//GEN-LAST:event_btnsumaActionPerformed

    private void btnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaActionPerformed
        double n1 = Double.parseDouble(primer1.getText());
        double n2 = Double.parseDouble(segundo1.getText());
        double resultado = Operar.resta(n1, n2);
        resultadotxt.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnrestaActionPerformed

    private void btnmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplicacionActionPerformed
        double n1 = Double.parseDouble(primer1.getText());
        double n2 = Double.parseDouble(segundo1.getText());
        double resultado = Operar.multiplicacion(n1, n2);
        resultadotxt.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnmultiplicacionActionPerformed

    private void btndivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivisionActionPerformed
        double n1 = Double.parseDouble(primer1.getText());
        double n2 = Double.parseDouble(segundo1.getText());
        double resultado = Operar.division(n1, n2);
        resultadotxt.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btndivisionActionPerformed

    private void btnpotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpotenciaActionPerformed
        double n1 = Double.parseDouble(primer1.getText());
        double n2 = Double.parseDouble(segundo1.getText());
        double resultado = Operar.potencia(n1, n2);
        resultadotxt.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnpotenciaActionPerformed

    private void btnlogaritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogaritmoActionPerformed
        double n1 = Double.parseDouble(primer1.getText());
        double resultado = Operar.logaritmo(n1);
        resultadotxt.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnlogaritmoActionPerformed

    private void btnraizcubicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnraizcubicaActionPerformed
         double n1 = Double.parseDouble(primer1.getText());
        double resultado = Operar.raizcubica(n1);
        resultadotxt.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnraizcubicaActionPerformed

    private void btnraizcuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnraizcuadradaActionPerformed
        double n1 = Double.parseDouble(primer1.getText());
        double resultado = Operar.raizcuadrada(n1);
        resultadotxt.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnraizcuadradaActionPerformed

    private void resultadotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadotxtActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        primer1.setText("");
        segundo1.setText("");
        resultadotxt.setText("");
    }//GEN-LAST:event_jButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndivision;
    private javax.swing.JButton btnlogaritmo;
    private javax.swing.JButton btnmultiplicacion;
    private javax.swing.JButton btnpotencia;
    private javax.swing.JButton btnraizcuadrada;
    private javax.swing.JButton btnraizcubica;
    private javax.swing.JButton btnresta;
    private javax.swing.JButton btnsuma;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField primer1;
    private javax.swing.JTextField resultadotxt;
    private javax.swing.JTextField segundo1;
    // End of variables declaration//GEN-END:variables
}
